"""
Mini-ORM — ACCEPTANCE SUITE
===========================

This file *is* the objective. "Which direction should we take?" is answered
by: whichever internal architecture turns these tests green, level by level.

Run:
    pytest -q                          # everything (34 tests)
    pytest -q -m "must and not should" # the acceptance gate (28 tests)
    pytest -q -m l3                    # one level at a time (recommended)

Levels
    L1  Foundation      descriptors + registry + CREATE TABLE
    L2  CRUD            create / search / write / unlink + parameterized SQL
    L3  Many2one
    L4  One2many + Many2many
    L5  RecordSet       laziness + chaining
    L6  N+1             measured before / after
    L7  Computed field  (SHOULD — stretch)

Milestones (4-day module)
    end of day 2 : L1 + L2 green
    end of day 3 : L3 + L4 green
    end of day 4 : L5 + L6 green   <- acceptance
    L7 and every `should` test are bonus.

Rule: do not edit this file. Edit `orm_adapter.py`, or your ORM.
"""

import pytest

# --------------------------------------------------------------------------
# L1 — Foundation: field descriptors, model registry, schema generation
# --------------------------------------------------------------------------


@pytest.mark.must
@pytest.mark.l1
class TestL1Foundation:
    def test_fields_are_descriptors(self, models):
        """spec 5.1 — Field implements the descriptor protocol."""
        field = models.Customer.__dict__.get("name")
        assert field is not None, "'name' is not declared on the Customer class itself"
        assert hasattr(field, "__get__"), "Field must implement __get__"
        assert hasattr(field, "__set__"), "Field must implement __set__ (data descriptor)"

    def test_values_are_per_instance_not_per_class(self, models):
        """spec 5.1 — the classic 'shared mutable state' bug."""
        a = models.Customer.create({"name": "Ada", "city": "Liege", "vip": True})
        b = models.Customer.create({"name": "Grace", "city": "Namur", "vip": False})
        assert a.name == "Ada"
        assert b.name == "Grace"
        a.write({"name": "Ada L."})
        assert b.name == "Grace", "writing on one record leaked onto another"

    def test_registry_is_populated_by_the_metaclass(self, orm, models):
        """spec 5.2 — models discoverable at runtime by name."""
        assert orm.registry_lookup("customer") is models.Customer
        assert orm.registry_lookup("order") is models.Order
        assert orm.registry_lookup("tag") is models.Tag
        assert orm.registry_lookup("does_not_exist") is None

    def test_tables_exist_with_expected_columns(self, orm, models):
        """spec 5.3 — CREATE TABLE generated from the declared fields."""
        rows = orm.raw_sql(
            "SELECT column_name, data_type FROM information_schema.columns "
            "WHERE table_name = %s",
            (orm.table_name(models.Customer),),
        )
        columns = {name: dtype for name, dtype in rows}
        assert columns, "no table found for Customer"
        assert "id" in columns
        assert "name" in columns
        assert "city" in columns
        assert "vip" in columns

    def test_column_types_match_field_types(self, orm, models):
        rows = orm.raw_sql(
            "SELECT column_name, data_type FROM information_schema.columns "
            "WHERE table_name = %s",
            (orm.table_name(models.Order),),
        )
        columns = {name: dtype for name, dtype in rows}
        assert "character varying" in columns["reference"] or columns["reference"] == "text"
        assert columns["amount"] in ("integer", "bigint", "smallint")


# --------------------------------------------------------------------------
# L2 — CRUD
# --------------------------------------------------------------------------


@pytest.mark.must
@pytest.mark.l2
class TestL2Crud:
    def test_create_returns_a_record_with_an_id(self, models):
        rec = models.Customer.create({"name": "Ada", "city": "Liege", "vip": True})
        assert rec.id is not None
        assert rec.name == "Ada"
        assert rec.vip is True

    def test_search_with_a_domain(self, models):
        models.Customer.create({"name": "Ada", "city": "Liege", "vip": True})
        models.Customer.create({"name": "Grace", "city": "Namur", "vip": False})
        found = models.Customer.search([("city", "=", "Liege")])
        assert len(found) == 1
        assert found[0].name == "Ada"

    def test_search_empty_domain_returns_all(self, models):
        for i in range(3):
            models.Customer.create({"name": f"C{i}", "city": "Liege", "vip": False})
        assert len(models.Customer.search([])) == 3

    def test_search_comparison_and_in_operators(self, models):
        for i in range(5):
            models.Order.create({"reference": f"SO{i}", "amount": i * 100})
        assert len(models.Order.search([("amount", ">", 150)])) == 3
        ids = [r.id for r in models.Order.search([])][:2]
        assert len(models.Order.search([("id", "in", ids)])) == 2

    def test_write_persists_to_the_database(self, models):
        rec = models.Customer.create({"name": "Ada", "city": "Liege", "vip": False})
        rec.write({"city": "Hasselt"})
        reloaded = models.Customer.browse(rec.id)
        assert reloaded.city == "Hasselt", "write() did not reach the database"

    def test_unlink_removes_the_row(self, models):
        rec = models.Customer.create({"name": "Ada", "city": "Liege", "vip": False})
        rec.unlink()
        assert len(models.Customer.search([])) == 0

    def test_sql_injection_is_neutralised(self, orm, models):
        """spec 5.3 SHOULD — parameterized queries, tested as an attack."""
        payload = "Robert'); DROP TABLE " + orm.table_name(models.Customer) + "; --"
        models.Customer.create({"name": payload, "city": "Liege", "vip": False})
        found = models.Customer.search([("city", "=", "Liege")])
        assert len(found) == 1
        assert found[0].name == payload, "the value was not stored verbatim"
        rows = orm.raw_sql(
            "SELECT COUNT(*) FROM information_schema.tables WHERE table_name = %s",
            (orm.table_name(models.Customer),),
        )
        assert rows[0][0] == 1, "the table is gone — string-formatted SQL somewhere"


# --------------------------------------------------------------------------
# L3 — Many2one
# --------------------------------------------------------------------------


@pytest.mark.must
@pytest.mark.l3
class TestL3Many2one:
    def test_many2one_returns_a_record_not_an_id(self, models):
        customer = models.Customer.create({"name": "Ada", "city": "Liege", "vip": True})
        order = models.Order.create(
            {"reference": "SO001", "amount": 100, "customer": customer}
        )
        related = order.customer
        assert not isinstance(related, int), "many2one returned a raw id, not a record"
        assert related.name == "Ada"

    def test_many2one_creates_a_foreign_key_column(self, orm, models):
        rows = orm.raw_sql(
            "SELECT column_name FROM information_schema.columns WHERE table_name = %s",
            (orm.table_name(models.Order),),
        )
        columns = {r[0] for r in rows}
        assert any(c.startswith("customer") for c in columns), (
            f"no FK column for Order.customer, found: {sorted(columns)}"
        )

    def test_many2one_survives_a_reload(self, models):
        customer = models.Customer.create({"name": "Ada", "city": "Liege", "vip": True})
        order = models.Order.create(
            {"reference": "SO001", "amount": 100, "customer": customer}
        )
        assert models.Order.browse(order.id).customer.id == customer.id

    @pytest.mark.should
    def test_many2one_is_lazy(self, orm, models):
        """spec 5.4 SHOULD — no query until the related data is touched."""
        customer = models.Customer.create({"name": "Ada", "city": "Liege", "vip": True})
        order = models.Order.create(
            {"reference": "SO001", "amount": 100, "customer": customer}
        )
        reloaded = models.Order.browse(order.id)
        assert reloaded.reference == "SO001"
        orm.reset_queries()
        related = reloaded.customer
        assert orm.query_count() == 0, "accessing the m2o object already queried"
        assert related.name == "Ada"
        assert orm.query_count() >= 1, "reading the related field issued no query at all"


# --------------------------------------------------------------------------
# L4 — One2many & Many2many
# --------------------------------------------------------------------------


@pytest.mark.must
@pytest.mark.l4
class TestL4Relations:
    def test_one2many_reverse_lookup(self, models):
        customer = models.Customer.create({"name": "Ada", "city": "Liege", "vip": True})
        other = models.Customer.create({"name": "Grace", "city": "Namur", "vip": False})
        models.Order.create({"reference": "A1", "amount": 10, "customer": customer})
        models.Order.create({"reference": "A2", "amount": 20, "customer": customer})
        models.Order.create({"reference": "B1", "amount": 30, "customer": other})
        assert len(customer.orders) == 2
        assert {o.reference for o in customer.orders} == {"A1", "A2"}

    def test_one2many_is_empty_not_none(self, models):
        customer = models.Customer.create({"name": "Solo", "city": "Liege", "vip": False})
        assert len(customer.orders) == 0
        assert not customer.orders, "an empty recordset must be falsy"

    def test_many2many_junction_table_exists(self, orm):
        rows = orm.raw_sql(
            "SELECT COUNT(*) FROM information_schema.tables WHERE table_name = %s",
            (orm.m2m_table_name(),),
        )
        assert rows[0][0] == 1, "no junction table generated for Order.tags"

    def test_many2many_resolves_in_both_directions(self, models):
        tag_a = models.Tag.create({"name": "urgent"})
        tag_b = models.Tag.create({"name": "export"})
        order = models.Order.create({"reference": "SO001", "amount": 100})
        order.write({"tags": [tag_a, tag_b]})
        assert {t.name for t in order.tags} == {"urgent", "export"}
        assert order.id in [o.id for o in tag_a.orders], "reverse m2m accessor is broken"

    def test_many2many_is_shared_not_copied(self, models):
        tag = models.Tag.create({"name": "urgent"})
        o1 = models.Order.create({"reference": "SO001", "amount": 100})
        o2 = models.Order.create({"reference": "SO002", "amount": 200})
        o1.write({"tags": [tag]})
        o2.write({"tags": [tag]})
        assert len(tag.orders) == 2


# --------------------------------------------------------------------------
# L5 — RecordSet: laziness and chaining
# --------------------------------------------------------------------------


@pytest.mark.must
@pytest.mark.l5
class TestL5RecordSet:
    def test_search_returns_a_recordset_not_a_list(self, models, dataset):
        result = models.Order.search([])
        assert not isinstance(result, list), "search() must return a RecordSet object"

    def test_search_does_not_execute_immediately(self, orm, models, dataset):
        """spec 5.5 — the query fires on evaluation, not at search() time."""
        orm.reset_queries()
        result = models.Order.search([("amount", ">", 100)])
        assert orm.query_count() == 0, (
            f"search() executed {orm.query_count()} query/queries eagerly: "
            f"{orm.query_log()}"
        )
        assert len(result) > 0
        assert orm.query_count() >= 1, "evaluation issued no query"

    def test_bool_and_len_trigger_evaluation(self, orm, models, dataset):
        orm.reset_queries()
        result = models.Order.search([("amount", ">", 10_000)])
        assert orm.query_count() == 0
        assert bool(result) is False
        assert orm.query_count() >= 1

    def test_filtered_chains_and_narrows(self, models, dataset):
        result = models.Order.search([]).filtered(lambda r: r.amount > 140)
        assert len(result) == 9  # amounts are 100..149
        assert all(r.amount > 140 for r in result)

    def test_filtered_returns_a_chainable_recordset(self, models, dataset):
        result = (
            models.Order.search([])
            .filtered(lambda r: r.amount > 120)
            .filtered(lambda r: r.amount < 126)
        )
        assert len(result) == 5  # 121..125

    @pytest.mark.should
    def test_filtered_on_an_evaluated_recordset_does_not_requery(self, orm, models, dataset):
        """spec 5.5 SHOULD — narrowing without re-querying from scratch."""
        recordset = models.Order.search([])
        len(recordset)  # force evaluation
        orm.reset_queries()
        subset = recordset.filtered(lambda r: r.amount > 140)
        assert len(subset) == 9
        assert orm.query_count() == 0, (
            f"filtered() re-queried the database: {orm.query_log()}"
        )


# --------------------------------------------------------------------------
# L6 — N+1: measured, then fixed
# --------------------------------------------------------------------------


@pytest.mark.must
@pytest.mark.l6
class TestL6NPlusOne:
    def test_the_naive_pattern_really_is_n_plus_1(self, orm, models, dataset):
        """spec 5.6 — the problem must be *measurable*, not asserted."""
        with orm.without_prefetch():
            orders = models.Order.search([])
            orm.reset_queries()
            names = [order.customer.name for order in orders]
            naive = orm.query_count()
        assert len(names) == 50
        assert naive >= 50, (
            f"expected ~51 queries for the naive pattern, measured {naive}. "
            "Either without_prefetch() does not disable batching, or the "
            "counter does not count every statement."
        )

    def test_prefetch_collapses_the_query_count(self, orm, models, dataset):
        orders = models.Order.search([])
        len(orders)
        orm.reset_queries()
        orm.prefetch(orders, "customer")
        names = [order.customer.name for order in orders]
        fixed = orm.query_count()
        assert len(names) == 50
        assert fixed <= 3, (
            f"prefetch issued {fixed} queries, expected <= 3: {orm.query_log()}"
        )

    def test_the_improvement_is_at_least_tenfold(self, orm, models, dataset):
        with orm.without_prefetch():
            orders = models.Order.search([])
            orm.reset_queries()
            [order.customer.name for order in orders]
            naive = orm.query_count()

        orders = models.Order.search([])
        len(orders)
        orm.reset_queries()
        orm.prefetch(orders, "customer")
        [order.customer.name for order in orders]
        fixed = orm.query_count()

        assert naive >= 10 * fixed, f"naive={naive}, fixed={fixed} — not a real fix"

    @pytest.mark.should
    def test_prefetch_also_works_on_one2many(self, orm, models, dataset):
        customers = models.Customer.search([])
        len(customers)
        orm.reset_queries()
        orm.prefetch(customers, "orders")
        counts = [len(c.orders) for c in customers]
        assert sum(counts) == 50
        assert orm.query_count() <= 3, orm.query_log()


# --------------------------------------------------------------------------
# L7 — Computed field (stretch)
# --------------------------------------------------------------------------


@pytest.mark.should
@pytest.mark.l7
class TestL7Computed:
    def test_computed_value_is_correct(self, models):
        order = models.Order.create({"reference": "SO001", "amount": 100})
        assert order.amount_ttc == 121

    def test_computed_value_is_not_stale_after_a_write(self, models):
        order = models.Order.create({"reference": "SO001", "amount": 100})
        assert order.amount_ttc == 121
        order.write({"amount": 200})
        assert order.amount_ttc == 242, "computed value is stale — no invalidation"

    def test_computed_field_is_not_a_stored_column(self, orm, models):
        rows = orm.raw_sql(
            "SELECT column_name FROM information_schema.columns WHERE table_name = %s",
            (orm.table_name(models.Order),),
        )
        columns = {r[0] for r in rows}
        assert "amount_ttc" not in columns, (
            "amount_ttc is stored as a column — it must be derived by a method "
            "(storing it is a valid design, but not what this exercise checks)"
        )